---

nextcloud_onlyoffice_document_server_enabled: false

nextcloud_onlyoffice_document_server_container_image: "docker.io/onlyoffice/documentserver:7.2.1.34"

nextcloud_onlyoffice_document_server_systemd_required_services_list: ['docker.service']

# Controls whether the nextcloud-onlyoffice-document-server container exposes its HTTP port (tcp/80 in the container).
#
# Takes an "<ip>:<port>" or "<port>" value (e.g. "127.0.0.1:37180"), or empty string to not expose.
nextcloud_onlyoffice_document_server_container_http_host_bind_port: ""
