---

- name: Determine existing Postgres version (check PG_VERSION file)
  stat:
    path: "{{ nextcloud_postgres_data_path }}/PG_VERSION"
  register: result_pg_version_stat

- name: Determine existing Postgres version (read PG_VERSION file)
  slurp:
    src: "{{ nextcloud_postgres_data_path }}/PG_VERSION"
  register: result_pg_version
  when: "result_pg_version_stat.stat.exists"

- name: Determine existing Postgres version (default to empty)
  set_fact:
    pg_version: ""

- name: Determine existing Postgres version (make sense of PG_VERSION file)
  set_fact:
    pg_version: "{{ result_pg_version['content']|b64decode|replace('\n', '') }}"
  when: "result_pg_version_stat.stat.exists"

- name: Determine Postgres version to use (default to latest)
  set_fact:
    nextcloud_docker_image_postgres_to_use: "{{ nextcloud_docker_image_postgres_latest }}"

- name: Determine Postgres version to use (use 9.x, if detected)
  set_fact:
    nextcloud_docker_image_postgres_to_use: "{{ nextcloud_docker_image_postgres_v9 }}"
  when: "pg_version.startswith('9.')"

- name: Ensure postgres data path exists
  file:
    path: "{{ nextcloud_postgres_data_path }}"
    state: directory
    mode: 0700
    owner: "{{ nextcloud_user_username }}"
    group: "{{ nextcloud_user_username }}"

- name: Ensure postgres Docker image is pulled
  docker_image:
    name: "{{ nextcloud_docker_image_postgres_to_use }}"

- name: Ensure Postgres environment variables file created
  template:
    src: "{{ role_path }}/templates/env/{{ item }}.j2"
    dest: "{{ nextcloud_environment_variables_data_path }}/{{ item }}"
    mode: 0640
  with_items:
    - "env-postgres-pgsql-docker"
    - "env-postgres-server-docker"

- name: Ensure nextcloud-postgres-cli script created
  template:
    src: "{{ role_path }}/templates/usr-local-bin/nextcloud-postgres-cli.j2"
    dest: "/usr/local/bin/nextcloud-postgres-cli"
    mode: 0750

- name: Ensure nextcloud-postgres.service installed
  template:
    src: "{{ role_path }}/templates/systemd/nextcloud-postgres.service.j2"
    dest: "/etc/systemd/system/nextcloud-postgres.service"
    mode: 0644
