---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Nextcloud services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ nextcloud_services_list }}"

- name: Ensure Nextcloud services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ nextcloud_services_list }}"
