---

- name: Fail if Collabora not enabled
  ansible.builtin.fail:
    msg: "Before installing and making use of the OnlyOffice app, you need to install the OnlyOffice services (see `nextcloud_collabora_online_enabled`)"
  when: not nextcloud_collabora_online_enabled

- name: Ensure nextcloud-apache is started
  ansible.builtin.service:
    name: nextcloud-apache
    state: started
    daemon_reload: true
  register: nextcloud_start

- name: Wait a while, so that Nextcloud can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: nextcloud_start.changed | bool

- name: Configure Collabora app
  ansible.builtin.shell:
    cmd: "docker exec --user={{ nextcloud_user_uid }}:{{ nextcloud_user_gid }} nextcloud-apache php /var/www/html/occ --no-warnings config:app:set richdocuments {{ item.key }} --value=\"{{ item.value }}\""
  with_items:
    -
      key: wopi_url
      value: "https://{{ nextcloud_collabora_online_domain }}"